I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 273, in script
    python:
ScriptError: could not find label 'real'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-7.3.5-sdk/renpy/bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-7.3.5-sdk/renpy/main.py", line 578, in main
    run(restart)
  File "/Applications/renpy-7.3.5-sdk/renpy/main.py", line 143, in run
    renpy.execution.run_context(True)
  File "/Applications/renpy-7.3.5-sdk/renpy/execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 273, in script
    python:
  File "/Applications/renpy-7.3.5-sdk/renpy/script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'real'.

Darwin-19.2.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Morinaka Gakuen 1.0
Wed Aug 12 10:43:50 2020
